### ISSUE TITLE
Installation fails when ClimateTools is already installed

### ISSUE THREAD

**Issue by fidelthomet** [JuliaClimate/ClimatePlots.jl#15]
With ClimateTools v0.18.0 installed, running `Pkg.add("ClimatePlots")` fails.

```
(v1.3) pkg> add ClimatePlots
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package ClimatePlots [b71d359b]:
 ClimatePlots [b71d359b] log:
 ├─possible versions are: 0.1.0 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 0.1.0
 └─restricted by compatibility requirements with ClimateTools [4f4ee721] to versions: uninstalled — no versions left
   └─ClimateTools [4f4ee721] log:
     ├─possible versions are: [0.9.0, 0.10.0-0.10.1, 0.11.0-0.11.3, 0.12.0, 0.13.0, 0.14.0-0.14.5, 0.15.0, 0.16.0, 0.17.0, 0.18.0] or uninstalled
     └─restricted to versions 0.18.0 by an explicit requirement, leaving only versions 0.18.0
```

It seems to work when I first install `ClimatePlots` and then `ClimateTools`. But then it's stays on v0.16.0.

**Comment by Balinus** [comment]
i think this is because the tagged release that includes compatibility with 0.18 is still not merged yet.

https://github.com/JuliaRegistries/General/pull/8876

Hopefully, this will be handled soon.

**Comment by fidelthomet** [comment]
Alright, admittedly I only have limited experience with Julia and none at all with JuliaRegistries or conda, but browsing through the [details of the failed AutoMerge test](https://github.com/JuliaRegistries/General/pull/8876/checks?check_run_id=426105427) I spottet:
```
The Python package mpl_toolkits.basemap could not be found by pyimport. Usually this means
that you did not install mpl_toolkits.basemap in the Python version being used by PyCall.
```
Which might be related to https://github.com/JuliaClimate/ClimateTools.jl/issues/121.

**Comment by Balinus** [comment]
Yeah, the whole basemap functionality is a real pain (I should have gone with cartopy!). 

The automerge tests uses pip as far as I understood and basemap is not available in pip on python 3. This explains why the installation instructions points to using Anaconda.

**Comment by Balinus** [comment]
See this PR. Work in progress. https://github.com/JuliaClimate/ClimatePlots.jl/pull/16

**Comment by Balinus** [comment]
Can you try the `master` branch?

in Julia, you can enter the `pkg` mode by pressing `]`. Then `dev ClimatePlots`

**Comment by fidelthomet** [comment]
Yes, Installation works smoothly now! Though I didn't get `mapclimgrid` to actually plot something yet. It just returns
```
julia> mapclimgrid(C)
(true, PyObject <cartopy.mpl.geoaxes.GeoAxesSubplot object at 0x16f9fdf60>, PyObject <cartopy.crs.Robinson object at 0x12e1a62b0>, PyObject <matplotlib.colorbar.Colorbar object at 0x1700e73c8>)
```
I'll have more time to look into it tomorrow, and might create a new issue for that then

**Comment by Balinus** [comment]
Nice! Perhaps in this case it's just a matter of doing:

```julia
using PyPlot
PyPlot.show()
```
I think that your configuration of matplotlib will actually define the bahaviour.
https://matplotlib.org/tutorials/introductory/customizing.html#the-matplotlibrc-file

**Comment by Balinus** [comment]
New version (0.2.0) using cartopy has been merged. Now, the easiest way to install everything is to simply configure PyCall to use Julia's conda version (this is done by default).

If not set to the default behaviour, this can be done with the following command:

```julia
ENV["PYTHON"]=""
using Pkg;Pkg.build("PyCall")
```
I usually exit Julia, then re-enter and simply doing `using ClimatePlots` will install the appropriate package if not installed already.
